# Generated by Django 5.1.1 on 2024-09-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_profesor_mascota_cedula_alter_mascota_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
